### ISSUE TITLE
Hitbox for random dice on mobile might be too small

### ISSUE THREAD

**Issue by tsunami643** [tsunami643/tsunami643.github.io#11]
The dice is somewhat difficult to hit on mobile. Maybe remove the 'patch' image when on mobile and place the dice inside the text field?

Here's a mockup.
![Mockup](http://i.imgur.com/dWQSanc.png)

**Comment by jtburke** [comment]
Looks slick.

Maybe do the same on desktop?
And come up with something else for the patch icon, and at the same time make it easy to maintain?

**Comment by tsunami643** [comment]
Sure, doing the same on desktop would be good. I can write a new issue for the patch icon.
