### ISSUE TITLE
Hero Icons

### ISSUE THREAD

**Issue by jtburke** [tsunami643/tsunami643.github.io#13]
My friend complained that he had to type and couldn't just click on a hero.

We could probably make a nice grid of hero's (efficiently) and on mobile maybe just list them or something?

Would you be interested in this?

**Comment by tsunami643** [comment]
A grid would be fine, but making a full grid show on the first page load would make the site feel heavier than I would prefer.

Maybe it could reveal itself in the shade once a user clicks a button? Like, toggle it with a hamburger menu icon or something. Or make a subtle button above the quote that pushes down the entire site like the grid is hiding above? Same thing on mobile, except to reveal a list, perhaps accompanied by each [hero's minimap icon.](http://dota2.gamepedia.com/Minimap#Icons)

**Comment by jtburke** [comment]
<a href="http://jtburke.github.io/tsunami643.github.io/?">View it on the fork</a> what do you think?
