### ISSUE TITLE
Heroes don't load in IE 11

### ISSUE THREAD

**Issue by tsunami643** [tsunami643/tsunami643.github.io#17]
I hate IE as much as the next guy which is why I didn't really care when things were misaligned on my original site for IE, but it seems that heroes refuse to load on IE now. I'm 99% sure I have Javascript enabled in IE, but nothing seems to work. The autosuggest works and the random dice does input a hero name, but nothing loads.

**Comment by jtburke** [comment]
Will take a look into this soon :D sorry about the long wait.
